/*
Question:
Return all suppliers along with the total revenue generated by their
products, including suppliers with no product sales displayed as 0.00.
Use RIGHT JOIN only.

Business Requirement:
The procurement team wants a complete supplier revenue report — every
supplier must appear, and those with no product sales should show 0.00
rather than being excluded.

Approach:
1. Chain: order_details → products → suppliers (right-to-left preservation).
2. First RIGHT JOIN: order_details RIGHT JOIN products on product_id —
   preserves all products, including those never ordered.
3. Second RIGHT JOIN: [od + products] RIGHT JOIN suppliers on supplier_id —
   preserves all suppliers, even those whose products have never been sold.
   Net effect: suppliers is fully preserved (the rightmost table).
4. Aggregate revenue with SUM(); COALESCE converts NULL to 0.00 for
   suppliers with no sales (SUM returns NULL, not 0, for empty groups).
5. Cast to numeric and ROUND to 2 decimal places.
6. GROUP BY s.supplier_id and s.company_name.

LEFT JOIN equivalent (same result, clearer reading order):
   SELECT s.company_name,
       COALESCE(ROUND(SUM(od.quantity * od.unit_price * (1 - od.discount))::numeric, 2), 0)
   FROM suppliers s
   LEFT JOIN products p ON p.supplier_id = s.supplier_id
   LEFT JOIN order_details od ON od.product_id = p.product_id
   GROUP BY s.company_name, s.supplier_id;

Expected Output:
| company_name                      | total_revenue |
|-----------------------------------|---------------|
| Plutzer Lebensmittelgroßmärkte AG | 74906.01      |
| Exotic Liquids                    | 24567.80      |
| Supplier X                        | 0.00          |

Concepts Used:
- RIGHT JOIN (chained, two levels)
- GROUP BY
- Aggregate Functions (SUM)
- NULL Handling (COALESCE)
- ROUND / CAST

Complexity:
Medium
*/

SELECT
    s.company_name,
    COALESCE(
        ROUND(
            SUM(od.quantity * od.unit_price * (1 - od.discount))::numeric,
            2
        ),
        0
    ) AS total_revenue
FROM order_details od
RIGHT JOIN products p
    ON p.product_id = od.product_id
RIGHT JOIN suppliers s
    ON s.supplier_id = p.supplier_id
GROUP BY
    s.company_name,
    s.supplier_id;
