/*
Question:
Return all categories along with the total revenue generated by their
products, including categories with no sales displayed as 0.00.

Business Requirement:
The management team wants a complete category revenue report — every
category must appear, and those with no sales should show 0.00 rather
than being excluded or showing NULL.

Approach:
1. Start from categories and LEFT JOIN to products on category_id —
   preserving every category even if no products are assigned.
2. LEFT JOIN again to order_details on product_id — preserving categories
   whose products exist but have never been ordered.
   Both joins must remain LEFT JOIN: converting either to INNER JOIN
   silently drops categories with no products or no sales.
3. Calculate discounted revenue per line item:
   unit_price * quantity * (1 - discount).
4. Aggregate with SUM() at the category level.
5. Wrap in COALESCE(..., 0) — SUM() returns NULL (not 0) for empty
   groups, so COALESCE is required to display 0.00 for zero-sales categories.
6. Cast to numeric and ROUND to 2 decimal places.
7. GROUP BY both category_name and category_id.

Expected Output:
| category_name  | total_revenue |
|----------------|---------------|
| Beverages      | 267868.15     |
| Dairy Products | 234507.29     |
| Seafood        | 0.00          |

Concepts Used:
- LEFT JOIN (chained, two levels)
- GROUP BY
- Aggregate Functions (SUM)
- NULL Handling (COALESCE)
- ROUND / CAST

Complexity:
Medium
*/

select c.category_name,
coalesce(round(sum(od.unit_price*od.quantity*(1-od.discount))::numeric,2),0) as total_revenue
from categories c
left join products p on p.category_id = c.category_id
left join order_details od on od.product_id = p.product_id
group by c.category_name, c.category_id;
