/*
Question:
Calculate the total revenue generated by each product across all orders, where revenue is defined as unit_price * quantity * (1 - discount), summed at the product level.

Business Requirement:
The business wants to understand which products are generating the most revenue so that pricing, inventory, and discontinuation decisions can be made data-driven.

Approach:
1. Join products to order_details on product_id to bring in line-item-level sales data.
2. Calculate per-line revenue using unit_price * quantity * (1 - discount).
3. Aggregate (SUM) that expression at the product level using GROUP BY.
4. Round the result to 2 decimal places for clean currency display.
5. Sort by total revenue descending so the highest-revenue products appear first.

Expected Output:
| product_id | product_name | total_revenue |
|------------|--------------|---------------|
| 38 | Côte de Blaye | 149984.20 |
| 29 | Thüringer Rostbratwurst | 87736.40 |
| 59 | Raclette Courdavault | 76683.75 |

Concepts Used:
- INNER JOIN
- GROUP BY
- Aggregate Functions (SUM)
- Numeric Formatting (ROUND/CAST)

Complexity:
Easy
*/

SELECT
    p.product_id,
    p.product_name,
    ROUND(SUM(od.unit_price * od.quantity * (1 - od.discount))::numeric, 2) AS total_revenue
FROM products p
JOIN order_details od ON od.product_id = p.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_revenue DESC;
