/*
Question:
Calculate total discounted revenue generated by each product category by rolling up product-level sales through the category hierarchy.

Business Requirement:
The business wants to evaluate which categories are the strongest revenue drivers in order to prioritize supplier negotiations and shelf space/marketing focus.

Approach:
1. Start from categories and join to products on category_id to associate each product with its category.
2. Join products to order_details on product_id to bring in transaction-level revenue data.
3. Calculate discounted revenue per line item: unit_price * quantity * (1 - discount).
4. Aggregate with SUM() grouped by category.
5. Sort by total revenue descending.

Expected Output:
| category_id | category_name | total_revenue |
|-------------|---------------|---------------|
| 1 | Beverages | 267868.18 |
| 4 | Dairy Products | 234507.29 |
| 8 | Seafood | 141623.09 |

Concepts Used:
- INNER JOIN (multi-table)
- GROUP BY
- Aggregate Functions (SUM)

Complexity:
Easy
*/

SELECT
    c.category_id,
    c.category_name,
    ROUND(SUM(od.unit_price * od.quantity * (1 - od.discount))::numeric, 2) AS total_revenue
FROM categories c
JOIN products p ON p.category_id = c.category_id
JOIN order_details od ON od.product_id = p.product_id
GROUP BY c.category_id, c.category_name
ORDER BY total_revenue DESC;
